version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db_2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgres://postgres:root@postgres:5432/postgres"
    ports:
      - "3001:3001"
    command: [ "sh", "-c", "cd /app && pnpm start:dev"]

volumes:
  postgres_data:
    driver: local

