# docker-compose.yml (parte modificada)
services:
  postgres:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: md5  # Fuerza autenticación por password
    ports:
      - "5433:5432"
    networks:
      - branch_net  # Red renombrada

  app:
    environment:
      DATABASE_URL: "postgres://postgres:root@postgres:5432/postgres"
    networks:
      - branch_net
    depends_on:
      postgres:
        condition: service_healthy

networks:
  branch_net:
    name: branch_compose_network  # Nombre único explícito
    driver: bridge
