version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db_2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:  # Añade healthcheck
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - my_network

  app:
    build: .
    container_name: nestjs_app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgres://postgres:root@postgres:5432/postgres"
    ports:
      - "3001:3001"
    networks:
      - my_network
    command: [ "sh", "-c", "cd /app && pnpm start:dev"]

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge
